<?hh // strict

namespace SebastianBergmann\CodeCoverage\Report\Html\Renderer\Template;

use
  SebastianBergmann\CodeCoverage\Report\Html\Renderer\CommonTemplateVariables
;

class CodeFile {

  public static function renderTo(
    string $filename,
    CommonTemplateVariables $common,
    string $items,
    string $lines,
  ): bool {

    file_put_contents($filename, self::render($common, $items, $lines));
    return true;

  }

  public static function render(
    CommonTemplateVariables $common,
    string $items,
    string $lines,
  ): string {
    $buffer = '';
    $buffer .= '<!DOCTYPE html>';
    $buffer .= '<html lang="en">';
    $buffer .= '<head>';
    $buffer .= '<meta charset="UTF-8">';
    $buffer .= '<title>Code Coverage for '.$common->full_path.'</title>';
    $buffer .=
      '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
    $buffer .=
      '<link href="'.
      $common->path_to_root.
      'css/bootstrap.min.css" rel="stylesheet">';
    $buffer .=
      '<link href="'.$common->path_to_root.'css/style.css" rel="stylesheet">';
    $buffer .= '<!--[if lt IE 9]>';
    $buffer .=
      '<script src="'.$common->path_to_root.'js/html5shiv.min.js"></script>';
    $buffer .=
      '<script src="'.$common->path_to_root.'js/respond.min.js"></script>';
    $buffer .= '<![endif]-->';
    $buffer .= '</head>';
    $buffer .= '<body>';
    $buffer .= '<header>';
    $buffer .= '<div class="container">';
    $buffer .= '<div class="row">';
    $buffer .= '<div class="col-md-12">';
    $buffer .= '<ol class="breadcrumb">';
    $buffer .= $common->breadcrumbs;
    $buffer .= '</ol>';
    $buffer .= '</div>';
    $buffer .= '</div>';
    $buffer .= '</div>';
    $buffer .= '</header>';
    $buffer .= '<div class="container">';
    $buffer .= '<table class="table table-bordered">';
    $buffer .= '<thead>';
    $buffer .= '<tr>';
    $buffer .= '<td>&nbsp;</td>';
    $buffer .=
      '<td colspan="11"><div align="center"><strong>Code Coverage</strong></div></td>';
    $buffer .= '</tr>';
    $buffer .= '<tr>';
    $buffer .= '<td>&nbsp;</td>';
    $buffer .=
      '<td colspan="3"><div align="center"><strong>Classes and Traits</strong></div></td>';
    $buffer .=
      '<td colspan="5"><div align="center"><strong>Functions and Methods</strong></div></td>';
    $buffer .=
      '<td colspan="3"><div align="center"><strong>Lines</strong></div></td>';
    $buffer .= '</tr>';
    $buffer .= '</thead>';
    $buffer .= '<tbody>';
    $buffer .= $items;
    $buffer .= '</tbody>';
    $buffer .= '</table>';
    $buffer .=
      '<table id="code" class="table table-borderless table-condensed">';
    $buffer .= '<tbody>';
    $buffer .= $lines;
    $buffer .= '</tbody>';
    $buffer .= '</table>';
    $buffer .= '<footer>';
    $buffer .= '<hr/>';
    $buffer .= '<h4>Legend</h4>';
    $buffer .= '<p>';
    $buffer .= '<span class="success"><strong>Executed</strong></span>';
    $buffer .= '<span class="danger"><strong>Not Executed</strong></span>';
    $buffer .= '<span class="warning"><strong>Dead Code</strong></span>';
    $buffer .= '</p>';
    $buffer .= '<p>';
    $buffer .= '<small>Generated by ';
    $buffer .=
      '<a href="https://github.com/sebastianbergmann/php-code-coverage" target="_top">';
    $buffer .=
      'php-code-coverage '.
      $common->version.
      '</a> using '.
      $common->runtime.
      $common->generator;
    $buffer .= ' at '.$common->date.'.</small>';
    $buffer .= '</p>';
    $buffer .=
      '<a title="Back to the top" id="toplink" href="#"><span class="glyphicon glyphicon-arrow-up"></span></a>';
    $buffer .= '</footer>';
    $buffer .= '</div>';
    $buffer .=
      '<script src="'.
      $common->path_to_root.
      'js/jquery.min.js" type="text/javascript"></script>';
    $buffer .=
      '<script src="'.
      $common->path_to_root.
      'js/bootstrap.min.js" type="text/javascript"></script>';
    $buffer .=
      '<script src="'.
      $common->path_to_root.
      'js/holder.min.js" type="text/javascript"></script>';
    $buffer .= '<script type="text/javascript">';
    $buffer .= '$(function() {';
    $buffer .= 'var $window  = $(window), ';
    $buffer .= '$top_link = $(\'#toplink\'), ';
    $buffer .= '$body = $(\'body, html\'), ';
    $buffer .= 'offset = $(\'#code\').offset().top;';
    $buffer .= '$top_link.hide().click(function(event) {';
    $buffer .= 'event.preventDefault();';
    $buffer .= '$body.animate({scrollTop:0}, 800);';
    $buffer .= '});';
    $buffer .= '$window.scroll(function() {';
    $buffer .= 'if($window.scrollTop() > offset) {';
    $buffer .= '$top_link.fadeIn();';
    $buffer .= '} else {';
    $buffer .= '$top_link.fadeOut();';
    $buffer .= '}';
    $buffer .= '}).scroll();';
    $buffer .= '$(\'.popin\').popover({trigger: \'hover\'});';
    $buffer .= '});';
    $buffer .= '</script>';
    $buffer .= '</body>';
    $buffer .= '</html>';
    return $buffer;
  }

}
